name: 30-Full-CI 
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
        working-directory: node-app
      - run: npm run build
        working-directory: node-app
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm test
        working-directory: node-app
  
  quality:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Quality"
  
  ready:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ready"